insert into Products (id, name, description, price, category, available_stock_id) values (1, 'Barcelona', 'Camiseta Nike Barcelona Home 2021/2022 + Parche UEFA Champions League', '$15500', 'esnovedad', 1);
insert into Products (id, name, description, price, category, available_stock_id) values (2, 'España Retro', 'Camiseta Adidas España Retro Home 1998/1999 Dorsal 10 - Raul', '$15000', 'retro', 2);
insert into Products (id, name, description, price, category, available_stock_id) values (3, 'PSG', 'Camiseta Nike PSG Home 2021/2022', '$14500', 'esnovedad', 3);
insert into Products (id, name, description, price, category, available_stock_id) values (4, 'Alemania', 'Camiseta Adidas Alemania Home 2020/2021 + Parche Eurocopa', '$13000', 'selecciones', 4);
insert into Products (id, name, description, price, category, available_stock_id) values (5, 'Ajax Retro', 'Camiseta Adidas Ajax Home 1994/1995', '$15500', 'retro', 5);
insert into Products (id, name, description, price, category, available_stock_id) values (6, 'River', 'Camiseta Adidas River Home 2021/2022', '$11500', 'argentina', 6);
insert into Products (id, name, description, price, category, available_stock_id) values (7, 'Liverpool', 'Camiseta Nike Liverppol Home 2021/2022 + Parche UEFA Champions League', '$15500', 'europa', 7);
insert into Products (id, name, description, price, category, available_stock_id) values (8, 'España', 'Camiseta Adidas España Home 2021/2022', '$13000', 'selecciones', 8);
insert into Products (id, name, description, price, category, available_stock_id) values (9, 'Boca', 'Camiseta Adidas Boca Home 2021/2022', '$11500', 'argentina', 9);
insert into Products (id, name, description, price, category, available_stock_id) values (10, 'Suecia Retro', 'Camiseta Adidas Suecia Retro Home 1996/1998 Dorsal 7 - Larsson', '$15000', 'Comedy|Drama|Romance', 10);
insert into Products (id, name, description, price, category, available_stock_id) values (11, 'Inter', 'Camiseta Nike Inter Home 2020/2021', '$13500', 'europa', 11);
insert into Products (id, name, description, price, category, available_stock_id) values (12, 'Holanda Retro', 'Camiseta Nike Holanda Home 1994 Dorsal 10 - Bergkamp', '$15000', 'retro', 12);
insert into Products (id, name, description, price, category, available_stock_id) values (13, 'Racing', 'Camiseta Kappa Racing Home 2021/2022', '$10000', 'argentina', 13);
insert into Products (id, name, description, price, category, available_stock_id) values (14, 'Francia', 'Camiseta Nike Francia Home Vapor Match 2020/2021', '$16500', 'europa', 14);
insert into Products (id, name, description, price, category, available_stock_id) values (15, 'Croacia', 'Camiseta Nike Croacia Away 2020/2021', '$13000', 'europa', 15);
insert into Products (id, name, description, price, category, available_stock_id) values (16, 'Manchester City', 'Camiseta Puma Manchester City Home 2021/2022', '$14500', 'europa', 16);
insert into Products (id, name, description, price, category, available_stock_id) values (17, 'Independiente', 'Camiseta Puma Independiente Home 2021/2022', '$10000', 'argentina', 17);
insert into Products (id, name, description, price, category, available_stock_id) values (18, 'Holanda', 'Camiseta Nike Holanda Home Vapor Match 2021/2022', '$16500', 'selecciones', 18);
insert into Products (id, name, description, price, category, available_stock_id) values (19, 'Real Madrid', 'Camiseta Adidas Real Madrid Home 2021/2022', '$14500', 'europa', 19);
insert into Products (id, name, description, price, category, available_stock_id) values (20, 'Juventus', 'Camiseta Adidas Juventus Home 2021/2022', '$13500', 'europa', 20);
